/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PuButton {
        "disabled": boolean;
        "type": 'filled' | 'filled-tonal' | 'outlined' | 'elevated' | 'text';
    }
    interface PuCard {
        "type": 'filled' | 'outlined' | 'elevated';
    }
    interface PuCheckbox {
        "checked": boolean;
        "disabled": boolean;
        "hasError": boolean;
    }
    interface PuFab {
        "type": 'small' | 'large';
    }
    interface PuIcon {
    }
    interface PuIconButtons {
        "disabled": boolean;
        "tooltip": string;
        "type": 'standart' | 'contained';
    }
    interface PuText {
        "type": 'display-text' | 'display-text-large' | 'display-text-small' |
    'headline-text' | 'headline-text-large' | 'headline-text-small' |
    'title-text' | 'title-text-large' | 'title-text-small' |
    'body-text' | 'body-text-large' | 'body-text-small' |
    'label-text' | 'label-text-large' | 'label-text-small';
    }
}
declare global {
    interface HTMLPuButtonElement extends Components.PuButton, HTMLStencilElement {
    }
    var HTMLPuButtonElement: {
        prototype: HTMLPuButtonElement;
        new (): HTMLPuButtonElement;
    };
    interface HTMLPuCardElement extends Components.PuCard, HTMLStencilElement {
    }
    var HTMLPuCardElement: {
        prototype: HTMLPuCardElement;
        new (): HTMLPuCardElement;
    };
    interface HTMLPuCheckboxElement extends Components.PuCheckbox, HTMLStencilElement {
    }
    var HTMLPuCheckboxElement: {
        prototype: HTMLPuCheckboxElement;
        new (): HTMLPuCheckboxElement;
    };
    interface HTMLPuFabElement extends Components.PuFab, HTMLStencilElement {
    }
    var HTMLPuFabElement: {
        prototype: HTMLPuFabElement;
        new (): HTMLPuFabElement;
    };
    interface HTMLPuIconElement extends Components.PuIcon, HTMLStencilElement {
    }
    var HTMLPuIconElement: {
        prototype: HTMLPuIconElement;
        new (): HTMLPuIconElement;
    };
    interface HTMLPuIconButtonsElement extends Components.PuIconButtons, HTMLStencilElement {
    }
    var HTMLPuIconButtonsElement: {
        prototype: HTMLPuIconButtonsElement;
        new (): HTMLPuIconButtonsElement;
    };
    interface HTMLPuTextElement extends Components.PuText, HTMLStencilElement {
    }
    var HTMLPuTextElement: {
        prototype: HTMLPuTextElement;
        new (): HTMLPuTextElement;
    };
    interface HTMLElementTagNameMap {
        "pu-button": HTMLPuButtonElement;
        "pu-card": HTMLPuCardElement;
        "pu-checkbox": HTMLPuCheckboxElement;
        "pu-fab": HTMLPuFabElement;
        "pu-icon": HTMLPuIconElement;
        "pu-icon-buttons": HTMLPuIconButtonsElement;
        "pu-text": HTMLPuTextElement;
    }
}
declare namespace LocalJSX {
    interface PuButton {
        "disabled"?: boolean;
        "type"?: 'filled' | 'filled-tonal' | 'outlined' | 'elevated' | 'text';
    }
    interface PuCard {
        "type"?: 'filled' | 'outlined' | 'elevated';
    }
    interface PuCheckbox {
        "checked"?: boolean;
        "disabled"?: boolean;
        "hasError"?: boolean;
    }
    interface PuFab {
        "type"?: 'small' | 'large';
    }
    interface PuIcon {
    }
    interface PuIconButtons {
        "disabled"?: boolean;
        "tooltip"?: string;
        "type"?: 'standart' | 'contained';
    }
    interface PuText {
        "type"?: 'display-text' | 'display-text-large' | 'display-text-small' |
    'headline-text' | 'headline-text-large' | 'headline-text-small' |
    'title-text' | 'title-text-large' | 'title-text-small' |
    'body-text' | 'body-text-large' | 'body-text-small' |
    'label-text' | 'label-text-large' | 'label-text-small';
    }
    interface IntrinsicElements {
        "pu-button": PuButton;
        "pu-card": PuCard;
        "pu-checkbox": PuCheckbox;
        "pu-fab": PuFab;
        "pu-icon": PuIcon;
        "pu-icon-buttons": PuIconButtons;
        "pu-text": PuText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pu-button": LocalJSX.PuButton & JSXBase.HTMLAttributes<HTMLPuButtonElement>;
            "pu-card": LocalJSX.PuCard & JSXBase.HTMLAttributes<HTMLPuCardElement>;
            "pu-checkbox": LocalJSX.PuCheckbox & JSXBase.HTMLAttributes<HTMLPuCheckboxElement>;
            "pu-fab": LocalJSX.PuFab & JSXBase.HTMLAttributes<HTMLPuFabElement>;
            "pu-icon": LocalJSX.PuIcon & JSXBase.HTMLAttributes<HTMLPuIconElement>;
            "pu-icon-buttons": LocalJSX.PuIconButtons & JSXBase.HTMLAttributes<HTMLPuIconButtonsElement>;
            "pu-text": LocalJSX.PuText & JSXBase.HTMLAttributes<HTMLPuTextElement>;
        }
    }
}
