/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PuButton {
        "disabled": boolean;
        "type": 'filled' | 'filled-tonal' | 'outlined' | 'elevated' | 'text';
    }
    interface PuCard {
        "type": 'filled' | 'outlined' | 'elevated';
    }
    interface PuText {
        "type": 'display-text' | 'display-text-large' | 'display-text-small' |
    'headline-text' | 'headline-text-large' | 'headline-text-small' |
    'title-text' | 'title-text-large' | 'title-text-small' |
    'body-text' | 'body-text-large' | 'body-text-small' |
    'label-text' | 'label-text-large' | 'label-text-small';
    }
}
declare global {
    interface HTMLPuButtonElement extends Components.PuButton, HTMLStencilElement {
    }
    var HTMLPuButtonElement: {
        prototype: HTMLPuButtonElement;
        new (): HTMLPuButtonElement;
    };
    interface HTMLPuCardElement extends Components.PuCard, HTMLStencilElement {
    }
    var HTMLPuCardElement: {
        prototype: HTMLPuCardElement;
        new (): HTMLPuCardElement;
    };
    interface HTMLPuTextElement extends Components.PuText, HTMLStencilElement {
    }
    var HTMLPuTextElement: {
        prototype: HTMLPuTextElement;
        new (): HTMLPuTextElement;
    };
    interface HTMLElementTagNameMap {
        "pu-button": HTMLPuButtonElement;
        "pu-card": HTMLPuCardElement;
        "pu-text": HTMLPuTextElement;
    }
}
declare namespace LocalJSX {
    interface PuButton {
        "disabled"?: boolean;
        "type"?: 'filled' | 'filled-tonal' | 'outlined' | 'elevated' | 'text';
    }
    interface PuCard {
        "type"?: 'filled' | 'outlined' | 'elevated';
    }
    interface PuText {
        "type"?: 'display-text' | 'display-text-large' | 'display-text-small' |
    'headline-text' | 'headline-text-large' | 'headline-text-small' |
    'title-text' | 'title-text-large' | 'title-text-small' |
    'body-text' | 'body-text-large' | 'body-text-small' |
    'label-text' | 'label-text-large' | 'label-text-small';
    }
    interface IntrinsicElements {
        "pu-button": PuButton;
        "pu-card": PuCard;
        "pu-text": PuText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pu-button": LocalJSX.PuButton & JSXBase.HTMLAttributes<HTMLPuButtonElement>;
            "pu-card": LocalJSX.PuCard & JSXBase.HTMLAttributes<HTMLPuCardElement>;
            "pu-text": LocalJSX.PuText & JSXBase.HTMLAttributes<HTMLPuTextElement>;
        }
    }
}
