/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Color } from "./interface";
export { Color } from "./interface";
export namespace Components {
    interface PuBadge {
    }
    interface PuBottomAppBars {
    }
    interface PuButton {
        "buttonType": string;
        "color"?: Color;
        "disabled": boolean;
        "expand"?: 'full' | 'block';
        "fill"?: 'filled' | 'filled-tonal' | 'outlined' | 'elevated' | 'text';
    }
    interface PuCard {
    }
    interface PuCarousel {
        "item": number;
    }
    interface PuCheckbox {
        "disabled": boolean;
    }
    interface PuChips {
        "type": "label" | "trailing" | 'text';
    }
    interface PuDatePicker {
        "months": string[];
        "weekDays": string[];
    }
    interface PuDialog {
    }
    interface PuIcon {
        "fill"?: 'outlined' | 'filled';
    }
    interface PuInput {
        "disabled": boolean;
        "placeholder"?: string;
    }
    interface PuNavigationBar {
    }
    interface PuTabs {
    }
}
declare global {
    interface HTMLPuBadgeElement extends Components.PuBadge, HTMLStencilElement {
    }
    var HTMLPuBadgeElement: {
        prototype: HTMLPuBadgeElement;
        new (): HTMLPuBadgeElement;
    };
    interface HTMLPuBottomAppBarsElement extends Components.PuBottomAppBars, HTMLStencilElement {
    }
    var HTMLPuBottomAppBarsElement: {
        prototype: HTMLPuBottomAppBarsElement;
        new (): HTMLPuBottomAppBarsElement;
    };
    interface HTMLPuButtonElement extends Components.PuButton, HTMLStencilElement {
    }
    var HTMLPuButtonElement: {
        prototype: HTMLPuButtonElement;
        new (): HTMLPuButtonElement;
    };
    interface HTMLPuCardElement extends Components.PuCard, HTMLStencilElement {
    }
    var HTMLPuCardElement: {
        prototype: HTMLPuCardElement;
        new (): HTMLPuCardElement;
    };
    interface HTMLPuCarouselElement extends Components.PuCarousel, HTMLStencilElement {
    }
    var HTMLPuCarouselElement: {
        prototype: HTMLPuCarouselElement;
        new (): HTMLPuCarouselElement;
    };
    interface HTMLPuCheckboxElement extends Components.PuCheckbox, HTMLStencilElement {
    }
    var HTMLPuCheckboxElement: {
        prototype: HTMLPuCheckboxElement;
        new (): HTMLPuCheckboxElement;
    };
    interface HTMLPuChipsElement extends Components.PuChips, HTMLStencilElement {
    }
    var HTMLPuChipsElement: {
        prototype: HTMLPuChipsElement;
        new (): HTMLPuChipsElement;
    };
    interface HTMLPuDatePickerElement extends Components.PuDatePicker, HTMLStencilElement {
    }
    var HTMLPuDatePickerElement: {
        prototype: HTMLPuDatePickerElement;
        new (): HTMLPuDatePickerElement;
    };
    interface HTMLPuDialogElement extends Components.PuDialog, HTMLStencilElement {
    }
    var HTMLPuDialogElement: {
        prototype: HTMLPuDialogElement;
        new (): HTMLPuDialogElement;
    };
    interface HTMLPuIconElement extends Components.PuIcon, HTMLStencilElement {
    }
    var HTMLPuIconElement: {
        prototype: HTMLPuIconElement;
        new (): HTMLPuIconElement;
    };
    interface HTMLPuInputElement extends Components.PuInput, HTMLStencilElement {
    }
    var HTMLPuInputElement: {
        prototype: HTMLPuInputElement;
        new (): HTMLPuInputElement;
    };
    interface HTMLPuNavigationBarElement extends Components.PuNavigationBar, HTMLStencilElement {
    }
    var HTMLPuNavigationBarElement: {
        prototype: HTMLPuNavigationBarElement;
        new (): HTMLPuNavigationBarElement;
    };
    interface HTMLPuTabsElement extends Components.PuTabs, HTMLStencilElement {
    }
    var HTMLPuTabsElement: {
        prototype: HTMLPuTabsElement;
        new (): HTMLPuTabsElement;
    };
    interface HTMLElementTagNameMap {
        "pu-badge": HTMLPuBadgeElement;
        "pu-bottom-app-bars": HTMLPuBottomAppBarsElement;
        "pu-button": HTMLPuButtonElement;
        "pu-card": HTMLPuCardElement;
        "pu-carousel": HTMLPuCarouselElement;
        "pu-checkbox": HTMLPuCheckboxElement;
        "pu-chips": HTMLPuChipsElement;
        "pu-date-picker": HTMLPuDatePickerElement;
        "pu-dialog": HTMLPuDialogElement;
        "pu-icon": HTMLPuIconElement;
        "pu-input": HTMLPuInputElement;
        "pu-navigation-bar": HTMLPuNavigationBarElement;
        "pu-tabs": HTMLPuTabsElement;
    }
}
declare namespace LocalJSX {
    interface PuBadge {
    }
    interface PuBottomAppBars {
    }
    interface PuButton {
        "buttonType"?: string;
        "color"?: Color;
        "disabled"?: boolean;
        "expand"?: 'full' | 'block';
        "fill"?: 'filled' | 'filled-tonal' | 'outlined' | 'elevated' | 'text';
    }
    interface PuCard {
    }
    interface PuCarousel {
        "item"?: number;
    }
    interface PuCheckbox {
        "disabled"?: boolean;
    }
    interface PuChips {
        "type"?: "label" | "trailing" | 'text';
    }
    interface PuDatePicker {
        "months"?: string[];
        "weekDays"?: string[];
    }
    interface PuDialog {
    }
    interface PuIcon {
        "fill"?: 'outlined' | 'filled';
    }
    interface PuInput {
        "disabled"?: boolean;
        "placeholder"?: string;
    }
    interface PuNavigationBar {
    }
    interface PuTabs {
    }
    interface IntrinsicElements {
        "pu-badge": PuBadge;
        "pu-bottom-app-bars": PuBottomAppBars;
        "pu-button": PuButton;
        "pu-card": PuCard;
        "pu-carousel": PuCarousel;
        "pu-checkbox": PuCheckbox;
        "pu-chips": PuChips;
        "pu-date-picker": PuDatePicker;
        "pu-dialog": PuDialog;
        "pu-icon": PuIcon;
        "pu-input": PuInput;
        "pu-navigation-bar": PuNavigationBar;
        "pu-tabs": PuTabs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pu-badge": LocalJSX.PuBadge & JSXBase.HTMLAttributes<HTMLPuBadgeElement>;
            "pu-bottom-app-bars": LocalJSX.PuBottomAppBars & JSXBase.HTMLAttributes<HTMLPuBottomAppBarsElement>;
            "pu-button": LocalJSX.PuButton & JSXBase.HTMLAttributes<HTMLPuButtonElement>;
            "pu-card": LocalJSX.PuCard & JSXBase.HTMLAttributes<HTMLPuCardElement>;
            "pu-carousel": LocalJSX.PuCarousel & JSXBase.HTMLAttributes<HTMLPuCarouselElement>;
            "pu-checkbox": LocalJSX.PuCheckbox & JSXBase.HTMLAttributes<HTMLPuCheckboxElement>;
            "pu-chips": LocalJSX.PuChips & JSXBase.HTMLAttributes<HTMLPuChipsElement>;
            "pu-date-picker": LocalJSX.PuDatePicker & JSXBase.HTMLAttributes<HTMLPuDatePickerElement>;
            "pu-dialog": LocalJSX.PuDialog & JSXBase.HTMLAttributes<HTMLPuDialogElement>;
            "pu-icon": LocalJSX.PuIcon & JSXBase.HTMLAttributes<HTMLPuIconElement>;
            "pu-input": LocalJSX.PuInput & JSXBase.HTMLAttributes<HTMLPuInputElement>;
            "pu-navigation-bar": LocalJSX.PuNavigationBar & JSXBase.HTMLAttributes<HTMLPuNavigationBarElement>;
            "pu-tabs": LocalJSX.PuTabs & JSXBase.HTMLAttributes<HTMLPuTabsElement>;
        }
    }
}
